"""Generate Rust energy-data source from the original Python seqfold tables.

Run from the repo root *before* the Python energy modules are removed:

    python3 codegen/gen_data.py

It imports the fully-built ``Energies`` objects (after the reverse-complement
``.update`` augmentation) so the emitted Rust maps are byte-for-byte identical
to what the Python implementation used.
"""

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.dirname(__file__) + "/.."))

from seqfold.dna import DNA_ENERGIES  # noqa: E402
from seqfold.rna import RNA_ENERGIES  # noqa: E402


def f(x) -> str:
    """Emit a Rust f64 literal that round-trips the Python float exactly."""
    return repr(float(x)) + "_f64"


def bp_map(name, d) -> str:
    items = ",\n    ".join(
        f'("{k}", ({f(v[0])}, {f(v[1])}))' for k, v in d.items()
    )
    return f"pub static {name}: &[(&str, (f64, f64))] = &[\n    {items},\n];\n"


def loop_map(name, d) -> str:
    items = ",\n    ".join(
        f"({int(k)}, ({f(v[0])}, {f(v[1])}))" for k, v in d.items()
    )
    return f"pub static {name}: &[(i64, (f64, f64))] = &[\n    {items},\n];\n"


def comp_map(name, d) -> str:
    items = ", ".join(f"(b'{k}', b'{v}')" for k, v in d.items())
    return f"pub static {name}: &[(u8, u8)] = &[{items}];\n"


def multibranch(name, t) -> str:
    return f"pub static {name}: (f64, f64, f64, f64) = ({f(t[0])}, {f(t[1])}, {f(t[2])}, {f(t[3])});\n"


def emit(prefix, e) -> str:
    out = []
    out.append(bp_map(f"{prefix}_NN", e.NN))
    out.append(bp_map(f"{prefix}_INTERNAL_MM", e.INTERNAL_MM))
    out.append(bp_map(f"{prefix}_TERMINAL_MM", e.TERMINAL_MM))
    out.append(bp_map(f"{prefix}_DE", e.DE))
    out.append(loop_map(f"{prefix}_BULGE_LOOPS", e.BULGE_LOOPS))
    out.append(loop_map(f"{prefix}_HAIRPIN_LOOPS", e.HAIRPIN_LOOPS))
    out.append(loop_map(f"{prefix}_INTERNAL_LOOPS", e.INTERNAL_LOOPS))
    out.append(comp_map(f"{prefix}_COMPLEMENT", e.COMPLEMENT))
    out.append(multibranch(f"{prefix}_MULTIBRANCH", e.MULTIBRANCH))
    if e.TRI_TETRA_LOOPS is not None:
        out.append(bp_map(f"{prefix}_TRI_TETRA_LOOPS", e.TRI_TETRA_LOOPS))
    return "\n".join(out)


def main():
    header = (
        "//! Energy tables for DNA and RNA folding.\n"
        "//!\n"
        "//! GENERATED by codegen/gen_data.py from the original seqfold Python\n"
        "//! energy parameters. Do not edit by hand; regenerate instead.\n"
        "#![cfg_attr(rustfmt, rustfmt::skip)]\n\n"
    )
    body = emit("DNA", DNA_ENERGIES) + "\n" + emit("RNA", RNA_ENERGIES)
    dest = os.path.abspath(
        os.path.dirname(__file__) + "/../src/core/data.rs"
    )
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w") as fh:
        fh.write(header + body)
    print("wrote", dest)


if __name__ == "__main__":
    main()
